### ISSUE TITLE
SyntaxError: Invalid regular expression flags

### ISSUE THREAD

**Issue by hitagiend** [ariakm25/GDriveDL#1]
hi, i got error when i tried run command:
```
[asus@asus-pc GDriveDL]$ gddl -b list.txt
/home/asus/GDriveDL/app.js:24
    id = url.match(/(file\/d\/|open\?id=)(.*?)(\/view|$)/si)[2];
                   ^

SyntaxError: Invalid regular expression flags
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

```
how am i supossed to do?

**Comment by anasrar** [comment]
let me check file ```list.txt``` please

**Comment by hitagiend** [comment]
it just standard shared google drive link, example
```
https://drive.google.com/file/d/0B8BNBtd_4hzSZXdpWndOTTYtOWs/view?usp=sharing
https://drive.google.com/file/d/0B8BNBtd_4hzSekxiSnU4TGV0eUE/view?usp=sharing
https://drive.google.com/file/d/0B8BNBtd_4hzSNkJjbXd3am9wNkE/view?usp=sharing
https://drive.google.com/file/d/0B8BNBtd_4hzSd3ZYQk5EOFE1ZWs/view?usp=sharing
https://drive.google.com/file/d/0B8BNBtd_4hzSMDNtNGVfWXk2X3c/view?usp=sharing
```
however I got the same outpun while ttied downloading single files.
for additional information, I running from Manjaro xfce with latest system and nodejs update

**Comment by anasrar** [comment]
![image](https://user-images.githubusercontent.com/38805204/59563915-39abbc00-906a-11e9-9fa4-ebb9ce3e0cc0.png)

nothing's wrong, it's work on my machine and my node js version is 11.14.0

**Comment by anasrar** [comment]
try to edit app.js
```js
const GetLink = (url, cb) => {
    id = url.match(/(file\/d\/|open\?id=)(.*?)(\/view|$)/si)[2];
    // ...
}
```
replace id to like this
```js
const GetLink = (url, cb) => {
    const id = url;
    // ...
}
```

and try ```node app -d "0B8BNBtd_4hzSZXdpWndOTTYtOWs"```
```node app -d "<IdFileGoogleDrive>"```

**Comment by hitagiend** [comment]
thank you for your assistance, now it's work like charm after edit app.js like you said

``const GetLink = (url, cb) => {
    const id = url;
``

however if i would to batches i have to modified my list.txt first with only inserting `"<IdFileGoogleDrive>"` onto my `list.txt` but it doesn't matter as long as it's work :D. once again, thank you, i'll mark this closed as well

![Screenshot_2019-06-17_00-45-44](https://user-images.githubusercontent.com/26172831/59567560-7c38bd00-9099-11e9-968e-9c63b86259f0.png)
